input {

  beats {
    port => 5044
    host => "0.0.0.0"
  }

  udp {
    port => 5045
    host => "0.0.0.0"
    buffer_size => 65536
    queue_size => 2000
    codec => json {
      target => "event_data"
    }
  }
}
