filter {
  if [agent][type] == "filebeat" and [log][file][path] =~ "iperf" {

    json {
      source => "message"
      skip_on_invalid_json => true
    }

    mutate {
      add_tag => ["iperf"]
      remove_field => ["message"]
    }
  }
}

output {
  if "iperf" in [tags] {
    elasticsearch {
      hosts => ["http://192.168.0.76:9200"]
      index => "iperf-%{+YYYY.MM.dd}"
    }
  }
}
