filter {
  if [event_data][robot] and [event_data][topic] {

    date {
      match => [ "[event_data][@timestamp]", "ISO8601" ]
      target => "@timestamp"
    }

    mutate {
      rename => {
        "[event_data][robot]" => "robot"
        "[event_data][topic]" => "topic"
        "[event_data][data]" => "data"
      }

      add_field => { "topic_index" => "%{topic}" }
    }

    mutate {
      gsub => [ "topic_index", "/", "" ]
      add_tag => ["ros2"]
    }
  }
}

output {
  if "ros2" in [tags] {
    elasticsearch {
      hosts => ["http://192.168.0.76:9200"]
      index => "ros2-%{robot}-%{topic_index}-%{+YYYY.MM.dd}"
    }
  }
}
