filter {
  if [event_data][topic] == "/suricata_alert" {

    date {
      match => [ "[event_data][@timestamp]", "ISO8601" ]
      target => "@timestamp"
    }

    mutate {
      rename => {
        "[event_data][robot]" => "robot"
        "[event_data][topic]" => "topic"
        "[event_data][data]" => "data"
      }
    }

    mutate {
      rename => {
        "[data][signature]" => "signature"
        "[data][severity]" => "severity"
        "[data][category]" => "category"
        "[data][src_ip]" => "src_ip"
        "[data][dest_ip]" => "dest_ip"
        "[data][proto]" => "proto"
      }
    }

    mutate {
      add_tag => ["suricata"]
      remove_field => ["data", "event_data"]
    }
  }
}

output {
  if "suricata" in [tags] {
    elasticsearch {
      hosts => ["http://192.168.0.76:9200"]
      index => "suricata-%{robot}-%{+YYYY.MM.dd}"
    }
  }
}
