input {
  http_poller {
    urls => {
      kismet_alerts => {
        method => get
        url => "http://10.0.0.2:2501/alerts/all_alerts.json?KISMET=1F6D9246B0A950AFE07CEE55B9E41179"
      }
    }
    request_timeout => 30
    schedule => { every => "5s" }
    codec => json
  }
}

filter {
  if [@metadata][input][http_poller][request][name] == "kismet_alerts" {
    mutate {
      add_tag => ["kismet"]
    }
  }
}
