input {
  udp {
    port => 5000
    codec => json
    tags => ["arp"]
    add_field => { "log_type" => "arp" }
  }
}

filter {
  if [log_type] == "arp" {

    split {
      field => "[arp_table]"
    }

    mutate {
      add_field => {
        "arp_timestamp" => "%{[timestamp]}"
        "ip"            => "%{[arp_table][ip]}"
        "mac"           => "%{[arp_table][mac]}"
        "interface"     => "%{[arp_table][interface]}"
      }
    }

    date {
      match  => [ "timestamp", "UNIX" ]
      target => "@timestamp"
    }

    mutate {
      rename => {
        "source_ip" => "[host][ip]"
      }
    }

    mutate {
      remove_field => [
        "arp_table",
        "@version",
        "message",
        "[event][original]",
        "timestamp"
      ]
    }
  }
}

output {
  if [log_type] == "arp" {
    elasticsearch {
      hosts => ["http://192.168.0.76:9200"]
      index => "arp-cache-%{robot}-%{+YYYY.MM.dd}"
    }
  }
}
